name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: ["1.11", "1.12", "1.13", "1.14", "1.15", "1.16", "1.17"]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build -v ./...
